## Discretization(Binning) 
It is the process of converting continuous variable into discrete variable by creating a set of contiguous interval that span the range of the variable's values.

Why?
1. To handle Outliers
2. To improve the value spread

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

### 1.Equal width /Uniform binning
in this technique we provide a range of bins to category our data like 0-10,10-20 etc ((max-min)/bins)

In [7]:
df2 = pd.read_csv('train.csv')
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [9]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])
df.head(10)

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500
5         0   NaN   8.4583
6         0  54.0  51.8625
7         0   2.0  21.0750
8         1  27.0  11.1333
9         1  14.0  30.0708

In [10]:
df.isna().sum()

Survived      0
Age         177
Fare          0
dtype: int64

In [12]:
# removing the missing value in the original data set 
df.dropna(inplace=True)
df.isna().sum()

Survived    0
Age         0
Fare        0
dtype: int64

In [14]:
df.shape
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [29]:
# extracting the data for labels and feature
X = df.iloc[:,1:3]
X

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
885  39.0  29.1250
886  27.0  13.0000
887  19.0  30.0000
889  26.0  30.0000
890  32.0   7.7500

[714 rows x 2 columns]

In [28]:
Y = df.iloc[:,0]
Y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=20)

In [31]:
y_train

833    0
218    1
272    1
537    1
314    0
      ..
271    1
278    0
338    1
600    1
442    0
Name: Survived, Length: 571, dtype: int64

In [32]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

In [33]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [34]:
y_predict = clf.predict(X_test)

In [35]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [36]:
accuracy_score(y_test,y_predict)

0.6293706293706294

In [38]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,Y,cv=10,scoring='accuracy'))

np.float64(0.6345266040688575)

## Binning

In [39]:
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [49]:
kbin_age = KBinsDiscretizer(n_bins=15,encode='ordinal',strategy='quantile')
kbin_fare = KBinsDiscretizer(n_bins=15,encode='ordinal',strategy='quantile')

KBinsDiscretizer(encode='ordinal', n_bins=15)

In [43]:
trf = ColumnTransformer([
    ('first',kbin_age,[0]),
    ('second',kbin_fare,[1])
])

In [44]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.fit_transform(X_test)

c:\Users\shiva\anaconda3\envs\ML_Learning\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
c:\Users\shiva\anaconda3\envs\ML_Learning\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
c:\Users\shiva\anaconda3\envs\ML_Learning\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
c:\Users\shiva\anaconda3\envs\ML_Learning\Lib\site-packages\sklearn\preprocessing\_discretization.py:304: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

In [45]:
trf.named_transformers_['first'].bin_edges_

array([array([ 0.42      ,  9.        , 15.93333333, 18.        , 20.        ,
              22.33333333, 24.8       , 27.26666667, 29.        , 30.2       ,
              34.        , 36.        , 41.6       , 48.13333333, 57.06666667,
              80.        ])                                                   ],
      dtype=object)

In [46]:
output = pd.DataFrame({
    'age':X_train['Age'],
    'age_trf':X_train_trf[:,0],
    'fare':X_train['Fare'],
    'fare_trf':X_train_trf[:,1]
})

array([[ 5.,  2.],
       [ 9., 13.],
       [12.,  7.],
       ...,
       [12.,  4.],
       [ 5.,  9.],
       [ 6.,  2.]], shape=(571, 2))

In [52]:
output['age_labels'] = pd.cut(x=X_train['Age'],
                                    bins=trf.named_transformers_['first'].bin_edges_[0].tolist())
output['fare_labels'] = pd.cut(x=X_train['Fare'],
                                    bins=trf.named_transformers_['second'].bin_edges_[0].tolist())

In [ ]:
output.sample(5)

      age  age_trf     fare  fare_trf      age_labels     fare_labels
548  33.0      9.0  20.5250       8.0    (30.2, 34.0]  (18.0, 23.442]
877  19.0      3.0   7.8958       3.0    (18.0, 20.0]  (7.854, 7.975]
106  21.0      4.0   7.6500       1.0  (20.0, 22.333]  (4.012, 7.741]
845  42.0     12.0   7.5500       1.0  (41.6, 48.133]  (4.012, 7.741]
866  27.0      7.0  13.8583       6.0  (24.8, 27.267]  (13.0, 15.726]