### Arbitary Imputation

In this technique we fill the entire missing value with the single value that inform the model that their is missing value.
Ex:- numerical missing value(-1,0,99.99 value that not presaent in the data) , categorical missing value(missing)

When to use ?
1. Not data missing at random (missing data in chuncks)

In [1]:
import numpy as  np 
import pandas as pd

In [4]:
df = pd.read_csv('titanic_toy.csv')
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [5]:
df.isna().mean()*100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

In [ ]:
# filling the missing value using pandas
df['Age_filled'] = df['Age'].fillna(0) # filled with zero

In [7]:
df['Fare_filled'] = df['Fare'].fillna(-1)

In [8]:
df.sample(7)

      Age      Fare  Family  Survived  Age_filled  Fare_filled
751   6.0   12.4750       1         1         6.0      12.4750
251  29.0       NaN       2         0        29.0      -1.0000
550  17.0  110.8833       2         1        17.0     110.8833
90   29.0    8.0500       0         0        29.0       8.0500
126   NaN    7.7500       0         0         0.0       7.7500
361  29.0   27.7208       1         0        29.0      27.7208
435  14.0  120.0000       3         1        14.0     120.0000

In [9]:
df.cov()

,Age,Fare,Family,Survived,Age_filled,Fare_filled
Age,211.019125,78.071438,-6.507525,-0.551296,211.019125,72.736744
Fare,78.071438,2530.673077,17.460363,6.442361,120.512869,2530.673077
Family,-6.507525,17.460363,2.603248,0.013063,-4.275157,16.641367
Survived,-0.551296,6.442361,0.013063,0.236772,0.090238,5.939859
Age_filled,211.019125,120.512869,-4.275157,0.090238,309.621823,110.361244
Fare_filled,72.736744,2530.673077,16.641367,5.939859,110.361244,2455.887436

In [10]:
df.corr()

                  Age      Fare    Family  Survived  Age_filled  Fare_filled
Age          1.000000  0.099481 -0.301914 -0.077221    1.000000     0.094827
Fare         0.099481  1.000000  0.212626  0.263920    0.135470     1.000000
Family      -0.301914  0.212626  1.000000  0.016639   -0.150584     0.208126
Survived    -0.077221  0.263920  0.016639  1.000000    0.010539     0.246324
Age_filled   1.000000  0.135470 -0.150584  0.010539    1.000000     0.126560
Fare_filled  0.094827  1.000000  0.208126  0.246324    0.126560     1.000000

In [11]:
df.describe()

              Age        Fare      Family    Survived  Age_filled  Fare_filled
count  714.000000  846.000000  891.000000  891.000000  891.000000   891.000000
mean    29.699118   32.279338    0.904602    0.383838   23.799293    30.598564
std     14.526497   50.305796    1.613459    0.486592   17.596074    49.556911
min      0.420000    0.000000    0.000000    0.000000    0.000000    -1.000000
25%     20.125000    7.895800    0.000000    0.000000    6.000000     7.895800
50%     28.000000   14.454200    0.000000    0.000000   24.000000    13.000000
75%     38.000000   31.206250    1.000000    1.000000   35.000000    30.070800
max     80.000000  512.329200   10.000000    1.000000   80.000000   512.329200

In [12]:
df['Age'].skew()

np.float64(0.38910778230082704)

In [13]:
df['Age_filled'].skew()

np.float64(0.2628619929342128)