### Handling categorical missing data

In this technique there are two ways to fill the missing value 
1. Fill with the frequent value
2. Fill with new category like (missing)

In [1]:
import numpy as np
import pandas as pd

In [30]:
df = pd.read_csv('train_2.csv')
df = pd.read_csv('train_2.csv',usecols=['GarageQual','FireplaceQu','SalePrice'])
df.head()

  FireplaceQu GarageQual  SalePrice
0         NaN         TA     208500
1          TA         TA     181500
2          TA         TA     223500
3          Gd         TA     140000
4          TA         TA     250000

In [8]:
df.isna().mean()*100

FireplaceQu    47.260274
GarageQual      5.547945
SalePrice       0.000000
dtype: float64

In [10]:
# finding the columns which has 5% missing data
cols = [var for var in df.columns 
        if df[var].isna().mean() < 0.06 and df[var].isna().mean() > 0.0]
cols

['GarageQual']

In [15]:
df.isna().sum()

FireplaceQu          690
GarageQual            81
SalePrice              0
GarageQual_filled      0
dtype: int64

In [16]:
df['GarageQual'].value_counts().sort_values(ascending=False)

GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64

In [18]:
df['FireplaceQu'].value_counts().sort_values(ascending=False)

FireplaceQu
Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: count, dtype: int64

In [17]:
# filling the missing value wit TA because it is more frequent
df['GarageQual_filled'] = df['GarageQual'].fillna('TA')

#### Using scikit learn

In [32]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='constant',fill_value='Missing')

In [31]:
cols = df.columns
df =  si.fit_transform(df)
df = pd.DataFrame(df,columns=cols)
df

     FireplaceQu GarageQual SalePrice
0        Missing         TA    208500
1             TA         TA    181500
2             TA         TA    223500
3             Gd         TA    140000
4             TA         TA    250000
...          ...        ...       ...
1455          TA         TA    175000
1456          TA         TA    210000
1457          Gd         TA    266500
1458     Missing         TA    142125
1459     Missing         TA    147500

[1460 rows x 3 columns]