### MEAN/MEDIAN Imputation

*In this teachnique we fill the missing value for  numerical features with the help of their mean and median values  of the features(columns). Here, we uses only single feature means only that feature where we have missing value to impute the missing value*

When to Use?
1. Mean :- if we have normal distribution data
2. Median :- if we have skewed data
3. MCAR
5. less than 5% missig data

In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('titanic_toy.csv')
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [ ]:
# finding the missing values percentage
df.isna().mean()*100

Age         19.865320
Fare         5.050505
Family       0.000000
Survived     0.000000
dtype: float64

In [9]:
# spliting the dataset into 2 input or output
X =df.iloc[:,0:3]
Y = df.iloc[:,3]
Y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [12]:
df.describe()

              Age        Fare      Family    Survived
count  714.000000  846.000000  891.000000  891.000000
mean    29.699118   32.279338    0.904602    0.383838
std     14.526497   50.305796    1.613459    0.486592
min      0.420000    0.000000    0.000000    0.000000
25%     20.125000    7.895800    0.000000    0.000000
50%     28.000000   14.454200    0.000000    0.000000
75%     38.000000   31.206250    1.000000    1.000000
max     80.000000  512.329200   10.000000    1.000000

### Using Pandas

In [23]:
Fare_mean = df['Fare'].mean()
Fare_median = df['Fare'].median()
Fare_mean

np.float64(32.279338297872336)

In [24]:
df['Fare_filled_mean'] = df['Fare'].fillna(Fare_mean)
df['Fare_filled_median'] = df['Fare'].fillna(Fare_median)
df.sample()

,Age,Fare,Family,Survived,Fare_filled,Fare_filled_mean,Fare_filled_median
299,50.0,247.5208,1,1,247.5208,247.5208,247.5208

In [25]:
df.corr()

,Age,Fare,Family,Survived,Fare_filled,Fare_filled_mean,Fare_filled_median
Age,1.000000,0.099481,-0.301914,-0.077221,0.097273,0.097273,0.096203
Fare,0.099481,1.000000,0.212626,0.263920,1.000000,1.000000,1.000000
Family,-0.301914,0.212626,1.000000,0.016639,0.209609,0.209609,0.209378
Survived,-0.077221,0.263920,0.016639,1.000000,0.256445,0.256445,0.251678
Fare_filled,0.097273,1.000000,0.209609,0.256445,1.000000,1.000000,0.996841
Fare_filled_mean,0.097273,1.000000,0.209609,0.256445,1.000000,1.000000,0.996841
Fare_filled_median,0.096203,1.000000,0.209378,0.251678,0.996841,0.996841,1.000000

In [26]:
df.cov()

,Age,Fare,Family,Survived,Fare_filled,Fare_filled_mean,Fare_filled_median
Age,211.019125,78.071438,-6.507525,-0.551296,73.727862,73.727862,73.196997
Fare,78.071438,2530.673077,17.460363,6.442361,2530.673077,2530.673077,2530.673077
Family,-6.507525,17.460363,2.603248,0.013063,16.577535,16.577535,16.611725
Survived,-0.551296,6.442361,0.013063,0.236772,6.116624,6.116624,6.021945
Fare_filled,73.727862,2530.673077,16.577535,6.116624,2402.717697,2402.717697,2402.717697
Fare_filled_mean,73.727862,2530.673077,16.577535,6.116624,2402.717697,2402.717697,2402.717697
Fare_filled_median,73.196997,2530.673077,16.611725,6.021945,2402.717697,2402.717697,2417.971600

### Using Scikit Learn

In [46]:
from sklearn.impute import SimpleImputer
si1 = SimpleImputer(strategy='mean')
si2 = SimpleImputer(strategy='median')

In [40]:
from sklearn.compose import ColumnTransformer

In [41]:
trf = ColumnTransformer([
    ('si1',si1,['Age']),
    ('si2',si2,['Fare'])]
    ,remainder='passthrough')

In [52]:
df['Fare_trf'] = si1.fit_transform(df[['Fare']])
df['Fare_trf'] = si2.fit_transform(df[['Fare']])

,Age,Fare,Family,Survived,Fare_filled,Fare_filled_mean,Fare_filled_median,Fare_trf
0,22.0,7.2500,1,0,7.2500,7.2500,7.2500,7.2500
1,38.0,71.2833,1,1,71.2833,71.2833,71.2833,71.2833
2,26.0,7.9250,0,1,7.9250,7.9250,7.9250,7.9250
3,35.0,53.1000,1,1,53.1000,53.1000,53.1000,53.1000
4,35.0,8.0500,0,0,8.0500,8.0500,8.0500,8.0500